name: "Test"
on: [push, workflow_dispatch]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true
      - run: vp install
      - run: vp format:ci
      - run: vp tsc
      - run: vp test
      - run: vp build
